### ISSUE TITLE
Access Control Headers : null with elasticsearch.js latest

### ISSUE THREAD

**Issue by unsalted** [spalger/elasticsearch-angular-example#2]
I've been trying to set things up using the latest version of elasticsearch.js based off this example.

I can't seem to get anywhere I keep getting:
``XMLHttpRequest cannot load http://localhost:9200/. The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://elasticsearch-angular-example.dev' is therefore not allowed access.``

This is how I am calling up the client:

```
ExampleApp.service('client', function (esFactory) {
      return esFactory({
        host: {
          protocol: 'http',
          host: localhost',
          port: 9200,
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          }
        }
      });
    });

```

Oddly enough if I drag and drop the index.html it seems not to care.  But in every other environment it turns up null.

**Comment by unsalted** [comment]
My bad it was an issue with the setup with elasticsearch and my use of anvil to run the file  - everything appears above board.

**Comment by spalger** [comment]
Glad to hear you got it figured out
