### ISSUE TITLE
How to load elastic-search-angular using webpack and es6

### ISSUE THREAD

**Issue by maanas** [spalger/elasticsearch-angular-example#4]
I m trying to use the elastic-search-angular client in angular app which i m trying to build using webpack with es6.
When i load the elastic-search-angular 
`import angularElasticsearch from 'elasticsearch-browser';`
I get this in npm start

```
WARNING in ./~/elasticsearch-browser/elasticsearch.js
Critical dependencies:
7:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/elasticsearch-browser/elasticsearch.js 7:418-425
```

And the browser complains:

```
Error: [$injector:modulerr] Failed to instantiate module function es() due to:
Error: Looks like you are expecting the previous "elasticsearch" module. It is now the "es" module. To create a client with this module use `new es.Client(params)`.
```

**Comment by maanas** [comment]
I tried to run this example as well which gives following error:
```
elasticsearch.angular.min.js:7 Uncaught Error: Cannot find module '__browserify_process'e @ elasticsearch.angular.min.js:7(anonymous function) @ elasticsearch.angular.min.js:7d.15.oh @ elasticsearch.angular.min.js:10e @ elasticsearch.angular.min.js:7a @ elasticsearch.angular.min.js:7(anonymous function) @ elasticsearch.angular.min.js:7(anonymous function) @ elasticsearch.angular.min.js:19
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=ExampleApp&p1=Error…angular-example-master%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A19)(anonymous function) @ angular.js:38(anonymous function) @ angular.js:4587q @ angular.js:322g @ angular.js:4548bb @ angular.js:4470c @ angular.js:1746yc @ angular.js:1767ee @ angular.js:1652(anonymous function) @ angular.js:30863b @ angular.js:3166Qf @ angular.js:3456Pf.d @ angular.js:3444
```

I m using elasticsearch 2.3.0 and i have enable cors as suggested

**Comment by maanas** [comment]
https://github.com/elastic/elasticsearch-js/issues/323
I think this is related with this issue.

**Comment by maanas** [comment]
When i tried to load the elasticsearch.angular.js file as global module by using import. Then i get the error 
bundle.js:8400 Uncaught ReferenceError: angular is not defined

**Comment by maanas** [comment]
I m able to get this working by loading the elasticsearch.angular file by
import '../node_modules/elasticsearch-browser/elasticsearch.angular';
There after i have to use the old convention of referring to the elasticsearch as 'elasticsearch'

I believe this is just a hack to get around and not the correct way to load using ES6 and webpack.

**Comment by ktsakas** [comment]
Seems to be fixed in the latest release candidate of elasticsearch-browser, try the following in package.json:

```
"dependencies": {
    "elasticsearch-browser": "^12.0.0-rc2"
}
```

**Comment by bvsrao** [comment]
"NetworkError: 404 Not Found - http://localhost:3000/public/elasticsearch-browser?bust=1484127266556"

included as 
import angularElasticsearch from 'elasticsearch-browser';

Not worked with elasticsearch-browser.

**Comment by bvsrao** [comment]
"elasticsearch-browser": "^12.1.3",   I already used latest Version

**Comment by spalger** [comment]
If you're trying to use angular then you need to require the angular version of the client and access the factory it exposes into angular dependency injection. 


in your webpack.config.js add an alias for the elasticsearch module:

```js
module.export = {
  entry: ...,
  output: { ... },
  resolve: {
    alias: {
      elasticsearch$: 'elasticsearch-browser/elasticsearch.angular`
    }
  }
}
```

Then in your code you import the `'elasticsearch'` module, depend on the elasticsearch angular modules, and import the `esFactory`:

```js
import 'angular';
import 'elasticsearch';

angular.module('myApp', ['elasticsearch'])
  .controller('AppController', (esFactory) => {
    const es = esFactory({
      host: 'http://localhost:9200'
    });

    es.search().then(...)
  });
```

**Comment by jovpet** [comment]
or simply edit your bower main files:

make sure you have this in bower file:

```bower
{
  "dependencies:  {
    "elasticsearch": "^12.1.3"
  },
  "overrides": {
    "elasticsearch": {
      "main": [
        "elasticsearch.angular.js"
      ]
    }
  }
}
```
